---
title: "Stats-Project-2-Part-2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Inputing the data into Variables and running the Anova test

```{r Processing data}
youtubeTimes <- c(72, 75, 72, 72, 72, 72, 72, 72)
prototypeTimes <- c(109, 182, 129, 201, 155, 180, 140, 90)

allTimes <- c(youtubeTimes, prototypeTimes)
groups <- c(rep("YouTube", length(youtubeTimes)), 
            rep("Prototype", length(prototypeTimes)))

mean(youtubeTimes)
sd(youtubeTimes)

mean(prototypeTimes)
sd(prototypeTimes)

```


```{r Anova}
times.anova <- aov(allTimes ~ groups)
summary(times.anova)
```


```{r T-Test}

t.test(youtubeTimes, prototypeTimes, paired = TRUE, alternative = "greater", conf.level = 0.95)

```


```{r, message = FALSE, warning = FALSE}
library(tidyverse)

results <- data.frame(youtubeTimes, prototypeTimes)

results

boxplot(results$prototypeTimes, ylab = "Prototype Times")


g <- ggplot(results, aes(x = youtubeTimes, y = prototypeTimes, group = youtubeTimes))
  g + geom_boxplot() + labs(x = "Youtube Times", y = "Prototype Times")

```


```{r}
youtubeTimes <- c(72, 75, 72, 72, 72, 72, 72, 72)
prototypeTimes <- c(109, 182, 129, 201, 155, 180, 140, 90)

df <- data.frame(Group = c(rep("YouTube", length(youtubeTimes)), rep("Prototype", length(prototypeTimes))),
                 Time = c(youtubeTimes, prototypeTimes))
                 
library(ggplot2)

ggplot(df, aes(x = Group, y = Time)) +
  geom_boxplot() +
  labs(x = "Group", y = "Time")                 
                 
```